using System.Net.Http;
using OutWit.Cloud.Data.Processing;
using OutWit.Controller.Render.Model;
using OutWit.Render.BlenderBridge.Channels.Interfaces;
using OutWit.Render.BlenderBridge.Contracts;
using OutWit.Render.BlenderBridge.Tests.Infrastructure.Hosting;
using static OutWit.Render.BlenderBridge.Tests.Infrastructure.Transport.BridgeRestTestUtils;

namespace OutWit.Render.BlenderBridge.LocalTests.Live
{
    /// <summary>
    /// Canonical live distribution tests: full-quality video renders that genuinely load the worker
    /// nodes (1080p, real sample counts, many frames) across all three engines, driven end-to-end
    /// through the Blender bridge (the exact path the addon uses). Unlike the preview-grade
    /// distribution tests (640×360 / 1 sample), these are heavy enough for the per-node split to
    /// reflect real work — open NODE ASSIGNMENTS in the admin UI to watch the balancing.
    ///
    /// Two kinds of input, per the canonical-test plan:
    ///   - REAL meaningful scenes from blender.org demo files dropped into <c>@Data/</c>
    ///     (cube_diorama, greasepencil-bike) — gitignored, self-skip when absent.
    ///   - ARTIFICIAL self-contained scenes committed under <c>@Data/canonical/</c> (generated by the
    ///     Python scripts in <c>Canonical/</c>) — always present, so the suite has a real animated
    ///     effect to render out of the box and serves as a worked example for plugin authors.
    ///
    /// Output MP4s land under <c>@Output/canonical/&lt;case&gt;/</c> for inspection.
    /// [Explicit] + env-gated on OMNIBUSCLOUD_API_KEY. Long timeout — real multi-frame renders.
    /// </summary>
    [TestFixture]
    [Explicit("Canonical full-quality live distribution workload against the deployed OmnibusCloud instance — watch NODE ASSIGNMENTS in the UI.")]
    [NonParallelizable]
    internal sealed class BridgeCanonicalDistributionTests
    {
        #region Constants

        private static readonly TimeSpan TIMEOUT = TimeSpan.FromMinutes(45);
        private static readonly TimeSpan POLL = TimeSpan.FromSeconds(5);

        #endregion

        #region Fields

        private LiveCloudConnectionService m_connection = null!;

        #endregion

        #region Setup

        [OneTimeSetUp]
        public async Task SetupAsync()
        {
            if (!LiveIntegrationSettings.IsConfigured)
                Assert.Ignore("Live integration skipped: set OMNIBUSCLOUD_API_KEY.");

            using var cts = new CancellationTokenSource(TimeSpan.FromMinutes(2));
            m_connection = new LiveCloudConnectionService(
                LiveIntegrationSettings.ServerUrl,
                LiveIntegrationSettings.IdentityUrl,
                LiveIntegrationSettings.ApiKey!);

            if (!await m_connection.EnsureConnectedAsync(cts.Token))
                Assert.Fail("Could not connect to the deployed OmnibusCloud API.");
        }

        [OneTimeTearDown]
        public async Task TearDownAsync()
        {
            if (m_connection != null)
                await m_connection.DisconnectAsync();
        }

        #endregion

        #region Cases

        public static IEnumerable<TestCaseData> CanonicalCases()
        {
            // caseName, benchmarkFallback, dataRelative, engine, resX, resY, samples, startFrame, endFrame, port

            // --- REAL meaningful scenes (blender.org demo files in @Data, gitignored, self-skip) ---
            yield return new TestCaseData(
                "real-cube-diorama-cycles", "benchmark_scene_still.blend", "cube_diorama/cube_diorama.blend",
                RenderEngine.Cycles, 1920, 1080, 128, 1, 48, 17870);
            yield return new TestCaseData(
                "real-bike-greasepencil", "benchmark_scene_video.blend", "greasepencil-bike.blend",
                RenderEngine.GreasePencil, 1920, 1080, 8, 1, 120, 17871);

            // --- ARTIFICIAL self-contained scenes (committed under @Data/canonical, always present) ---
            yield return new TestCaseData(
                "canonical-wave-cycles", "canonical_wave.blend", "canonical/canonical_wave.blend",
                RenderEngine.Cycles, 1920, 1080, 128, 1, 120, 17872);
            yield return new TestCaseData(
                "canonical-wave-eevee", "canonical_wave.blend", "canonical/canonical_wave.blend",
                RenderEngine.Eevee, 1920, 1080, 64, 1, 120, 17873);
            yield return new TestCaseData(
                "canonical-greasepencil", "canonical_greasepencil.blend", "canonical/canonical_greasepencil.blend",
                RenderEngine.GreasePencil, 1920, 1080, 8, 1, 120, 17874);
        }

        #endregion

        #region Tests

        [TestCaseSource(nameof(CanonicalCases))]
        public async Task CanonicalRenderVideoDistributedAcrossNodesLiveTest(
            string caseName, string benchmarkFallback, string dataRelative, RenderEngine engine,
            int resolutionX, int resolutionY, int samples, int startFrame, int endFrame, int port)
        {
            var scenePath = TestPaths.ResolveScene(benchmarkFallback, dataRelative);
            var expectedScript = $"RenderVideo{engine}";
            var frameCount = endFrame - startFrame + 1;

            await RunBridgeAsync(caseName, port, async (http, url, outputDir) =>
            {
                var upload = await UploadAsync(http, url, scenePath);
                var launch = await SendPostAsync<RunRenderVideoResponse>(
                    http, url, nameof(IBlenderBridgeChannel.RunRenderVideoAsync),
                    upload.BlobId, startFrame, endFrame, VideoRenderOptions(engine, resolutionX, resolutionY, samples), Video());

                Banner($"CANONICAL {caseName} submitted: JobId={launch.JobId}  ({engine}, {resolutionX}x{resolutionY}, {samples} spp, {frameCount} frames) — open NODE ASSIGNMENTS in the UI now");

                var job = await WaitForJobCompletionAsync(http, url, launch.JobId);
                var download = await SendGetAsync<DownloadResultResponse>(http, url, nameof(IBlenderBridgeChannel.DownloadResultAsync), launch.JobId.ToString());

                Assert.Multiple(() =>
                {
                    Assert.That(job.ScriptName, Is.EqualTo(expectedScript));
                    Assert.That(job.Status, Is.EqualTo("Completed"));
                    Assert.That(download.FileName, Does.EndWith(".mp4"));
                    Assert.That(download.FileSize, Is.GreaterThan(0));
                });
                TestContext.Progress.WriteLine($"CANONICAL {caseName} done: {download.FileName} ({download.FileSize} bytes) in {outputDir}");
            });
        }

        [Test]
        public async Task BigCyclesVideo200LiveTest()
        {
            // Deliberately large render-bound video to study balance at real scale: 1080p / 256 spp /
            // 200 frames of the procedural canonical wave (heavy: Wave modifier + subsurf + metallic
            // Cycles). Cycles chunk = clamp(ceil(200/48),1,8) = 5 → persistent-batch active (5 frames /
            // process, scene loaded once per chunk). At this scale render time per frame dominates the
            // fixed per-frame overhead, so node Rate should predict real wall and the split should be
            // well balanced (makespan even across nodes). Watch NODE ASSIGNMENTS in the admin UI.
            const RenderEngine engine = RenderEngine.Cycles;
            const int resX = 1920, resY = 1080, samples = 256, startFrame = 1, endFrame = 200;

            var scenePath = TestPaths.ResolveScene("canonical_wave.blend", "canonical/canonical_wave.blend");
            await RunBridgeAsync("big-cycles-video-200", 17880, async (http, url, outputDir) =>
            {
                var upload = await UploadAsync(http, url, scenePath);
                var launch = await SendPostAsync<RunRenderVideoResponse>(
                    http, url, nameof(IBlenderBridgeChannel.RunRenderVideoAsync),
                    upload.BlobId, startFrame, endFrame, VideoRenderOptions(engine, resX, resY, samples), Video());

                Banner($"BIG CYCLES VIDEO submitted: JobId={launch.JobId}  (1080p/256spp, {endFrame - startFrame + 1} frames) — open NODE ASSIGNMENTS in the UI now");

                var job = await WaitForJobCompletionAsync(http, url, launch.JobId);
                var download = await SendGetAsync<DownloadResultResponse>(http, url, nameof(IBlenderBridgeChannel.DownloadResultAsync), launch.JobId.ToString());

                Assert.Multiple(() =>
                {
                    Assert.That(job.ScriptName, Is.EqualTo("RenderVideoCycles"));
                    Assert.That(job.Status, Is.EqualTo("Completed"));
                    Assert.That(download.FileName, Does.EndWith(".mp4"));
                    Assert.That(download.FileSize, Is.GreaterThan(0));
                });
                TestContext.Progress.WriteLine($"BIG CYCLES VIDEO done: {download.FileName} ({download.FileSize} bytes) in {outputDir}");
            });
        }

        #endregion

        #region Tools

        private async Task RunBridgeAsync(string caseName, int port, Func<HttpClient, string, string, Task> body)
        {
            var localRestUrl = $"http://127.0.0.1:{port}/bridge/";
            var sessionDir = Path.Combine(Path.GetTempPath(), "BridgeCanonicalDistribution", Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(sessionDir);
            var outputDir = TestPaths.OutputDir("canonical", caseName);

            try
            {
                await using var bridgeHost = new BridgeLocalHost(
                    identityUrl: LiveIntegrationSettings.IdentityUrl,
                    localRestUrl: localRestUrl,
                    sessionDir: sessionDir,
                    cloudConnectionService: m_connection,
                    serverUrl: LiveIntegrationSettings.ServerUrl,
                    downloadCachePath: outputDir);
                await bridgeHost.StartAsync();
                using var http = new HttpClient();
                await body(http, localRestUrl, outputDir);
            }
            finally
            {
                if (Directory.Exists(sessionDir))
                {
                    try { Directory.Delete(sessionDir, recursive: true); }
                    catch { /* best-effort */ }
                }
            }
        }

        private static void Banner(string message)
        {
            TestContext.Progress.WriteLine("==================================================================");
            TestContext.Progress.WriteLine(message);
            TestContext.Progress.WriteLine("==================================================================");
        }

        private static Task<UploadBlendResponse> UploadAsync(HttpClient http, string localRestUrl, string scenePath)
            => SendGetAsync<UploadBlendResponse>(http, localRestUrl, nameof(IBlenderBridgeChannel.UploadBlendAsync), scenePath);

        private static RenderOptionsData VideoRenderOptions(RenderEngine engine, int resolutionX, int resolutionY, int samples)
        {
            return new RenderOptionsData
            {
                Format = RenderFormat.PNG,
                Engine = engine,
                Samples = samples,
                ResolutionX = resolutionX,
                ResolutionY = resolutionY,
                Denoise = engine == RenderEngine.Cycles
            };
        }

        private static VideoOptionsData Video()
        {
            return new VideoOptionsData { FrameRate = 24, ConstantRateFactor = 20 };
        }

        private static async Task<GetJobResponse> WaitForJobCompletionAsync(HttpClient http, string localRestUrl, Guid jobId)
        {
            var started = DateTime.UtcNow;
            string? last = null;
            while (DateTime.UtcNow - started < TIMEOUT)
            {
                var job = await SendGetAsync<GetJobResponse>(http, localRestUrl, nameof(IBlenderBridgeChannel.GetJobAsync), jobId.ToString());
                if (last != job.Status)
                {
                    TestContext.Progress.WriteLine($"Job {jobId}: {job.Status} ({job.OverallProgress:P0}) {job.ErrorMessage}");
                    last = job.Status;
                }

                if (string.Equals(job.Status, ProcessingJobStatus.Failed.ToString(), StringComparison.OrdinalIgnoreCase))
                {
                    if (!string.IsNullOrWhiteSpace(job.ErrorMessage) && job.ErrorMessage.Contains("No fallback nodes available", StringComparison.OrdinalIgnoreCase))
                        Assert.Ignore($"Skipped — deployed capacity unavailable: {job.ErrorMessage}");
                    Assert.Fail($"Job {jobId} failed: {job.ErrorMessage}");
                }

                if (job.IsCompleted)
                    return job;

                await Task.Delay(POLL);
            }

            Assert.Fail($"Job {jobId} did not complete within {TIMEOUT}.");
            return null!;
        }

        #endregion
    }
}
